# Generated by Django 4.1.7 on 2023-09-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_audio_article_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="thumb",
            field=models.ImageField(
                blank=True, default="default.jpg", upload_to="images/"
            ),
        ),
    ]
